import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@/public/static/css/BackgroundStyle.css"
import '@/public/static/css/ProfileStyle.css';
import ReduxProvider from "./_components/common/ReduxProvider";
import ThemeRegistry from "./_components/ThemeRegistry/ThemeRegistry";
import '@fontsource/dm-sans';
import '@fontsource/dm-sans/300.css';
import '@fontsource/dm-sans/400.css';
import '@fontsource/dm-sans/500.css';
import '@fontsource/dm-sans/700.css';
import '@fontsource/dm-sans/900.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "LTC Cloud",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // className={inter.className}
      >
        <ReduxProvider>
          <ThemeRegistry>{children}</ThemeRegistry>
        </ReduxProvider>
      </body>
    </html>
  );
}
